language: C
sudo: required
cache: ccache

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - ccache -M 0
  - ccache -F 0
  - sudo fallocate -l 8G /swapfile
  - sudo chmod 600 /swapfile
  - sudo mkswap /swapfile
  - sudo swapon /swapfile
  - export GITHUB_TOKEN="$GITHUB_TOKEN"
  - export release_repo="danascape/kernel-CI"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
  - sudo apt-get update
  - sudo apt-get install -y zstd adb autoconf automake axel bc bison build-essential clang cmake expat fastboot flex g++ g++-multilib gawk gcc gcc-multilib git-core gnupg gperf htop imagemagick lib32ncurses5-dev lib32z1-dev libtinfo5 libc6-dev libcap-dev libexpat1-dev libgmp-dev liblz4-* liblzma* libmpc-dev libmpfr-dev libncurses5-dev libsdl1.2-dev libssl-dev libtool libxml2 libxml2-utils lzma* lzop maven ncftp ncurses-dev patch patchelf pkg-config pngcrush pngquant python python-all-dev re2c schedtool squashfs-tools subversion texinfo unzip w3m xsltproc zip zlib1g-dev lzip p7zip-full binutils-aarch64-linux-gnu munge > /dev/null 2>&1
  - echo "deb http://archive.ubuntu.com/ubuntu disco main" >> /etc/apt/sources.list
  - echo "deb http://security.ubuntu.com/ubuntu disco-security main universe" >> /etc/apt/sources.list
  - sudo apt-get install libc6 > /dev/null 2>&1

before_script:
  - cd $HOME && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
script:
  - cd $HOME && git clone -b 12-06 https://github.com/iamsaalim/asus_X01AD --depth 1 kernel
  - cd $HOME/kernel
  - git clone https://github.com/stormbreaker-project/aarch64-linux-android-4.9 --depth 1 gcc
  - export PATH="$HOME/kernel/gcc/bin:$PATH"
  - export ARCH=arm64 SUBARCH=arm64
  - export KBUILD_BUILD_USER=danascape
  - export KBUILD_BUILD_HOST=travisCI
  - make O=out X01A-perf_defconfig ARCH=arm64
  - make -j$(nproc --all) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android-
  - git clone -b X01A https://github.com/stormbreaker-project/AnyKernel3
  - cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
  - wget https://raw.githubusercontent.com/stormbreaker-project/kernel-CI/gcc/modules.sh
  - chmod a+x modules.sh
  - source modules.sh
  - zip -r9 stormbreaker-x01a-test3.zip *
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "iamsaalim"
  - git config --local user.email "saalimquadri1@gmail.com"
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: $HOME/kernel/out/arch/arm64/boot/dts/dtbs.zip
  file: $HOME/kernel/AnyKernel3/stormbreaker-x01a-test3.zip
  skip_cleanup: true
  on:
    tags: true
    repo: stormbreaker-project/kernel-CI
    branch: master
