version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get install -y zstd adb autoconf automake axel bc bison build-essential clang cmake expat fastboot flex g++ g++-multilib gawk gcc gcc-multilib git-core gnupg gperf htop imagemagick lib32ncurses5-dev lib32z1-dev libtinfo5 libc6-dev libcap-dev libexpat1-dev libgmp-dev liblz4-* liblzma* libmpc-dev libmpfr-dev libncurses5-dev libsdl1.2-dev libssl-dev libtool libxml2 libxml2-utils lzma* lzop maven ncftp ncurses-dev patch patchelf pkg-config pngcrush pngquant python python-all-dev re2c schedtool squashfs-tools subversion texinfo unzip w3m xsltproc zip zlib1g-dev lzip p7zip-full binutils-aarch64-linux-gnu munge libc6 sudo wget
           git config --global user.name "iamsaalim"
           git config --global user.email "saalimquadri1@gmail.com"
           git config --global color.ui false
           mkdir kernel
           cd kernel
           wget https://raw.githubusercontent.com/stormbreaker-project/kernel-CI/proton/.circleci/build.sh
           source build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
