version: 2.1
parameters:
  device:
    type: string
    default: "none"
  branch:
    type: string
    default: "master"

jobs:
  build:
   docker:
      - image: starlight2834/ci_docker
   environment:
      DEVICE: << pipeline.parameters.device >>
      BRANCH: << pipeline.parameters.branch >>
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y install wget
           echo "Starting kernel build for << pipeline.parameters.device >>"
           wget https://raw.githubusercontent.com/stormbreaker-project/kernel-CI/master/.circleci/build.sh
           source build.sh $DEVICE $BRANCH

workflows:
  version: 2.1
  cooking:
    jobs:
      - build
